### ISSUE TITLE
Support for minitest 5.0.0

### ISSUE THREAD

**Issue by krainboltgreene** [qrush/m#35]
Doesn't work with latest minitest.

**Comment by philduffy** [comment]
I believe this was closed with [1.3.3](https://github.com/qrush/m/releases/tag/v1.3.3) :D

**Comment by zamith** [comment]
That is correct. It should be working fine. If you have any problems with it, please open issue.

I'll be closing this issue in favor of #43. Thanks everyone for the feedback.
