### ISSUE TITLE
Test run seems to return 0 status code even when tests fail/break

### ISSUE THREAD

**Issue by davidcpell** [qrush/m#56]
Hi `m`, 

Ran into an interesting edge case recently that I *think* has to do with `m`. Part of our Travis CI build process involved running our entire test suite with `bundle exec m -r test/`. We had an issue where the Travis build was passing even though a couple tests were breaking, i.e. the suite process was exiting with a 0 status.

When we changed our build process to use `bundle exec rake test:all` instead of `m`, the errors correctly resulted in a failing exit status and the build consequently failed.

Any thoughts on what would be causing this?

**Comment by davidcpell** [comment]
Looks like this has to do with the behavior of `Kernel#exit` vs `Kernel#exit!`. The latter has a `status` arg that defaults to `false`:

http://ruby-doc.org/core-2.2.3/Kernel.html#method-i-exit-21

`m.rb` has this:

`exit! Runner.new(argv).run`

Would you be open to a PR changing this to `exit!(true)`?

**Comment by zamith** [comment]
Thanks for all the info, I'll take a look into this as soon as possible.

**Comment by davidcpell** [comment]
You're welcome. If it is of any help, here is a dummy app I made for testing purposes:

https://github.com/davidcpell/m_exit_status_codes

I can reproduce the issue by running:

```
$ bundle exec m test/failing_test.rb
$ echo $!
```

Same with `error_test.rb`

**Comment by davidcpell** [comment]
This was resolved by 1783276b14fc81053f0e6fb8ae7cd726a32451a2
