### ISSUE TITLE
`m` incompatible with `shoulda` gem

### ISSUE THREAD

**Issue by davidcpell** [qrush/m#58]
Hi all,

It looks like `m` is unable to detect tests written with the use of `shoulda` keywords. A test like this:

```
should "do something" do
  # assertion
end
```

...causes an error like this, where all of the tests are found to be on lines that may not even exist:

```
✗ m test/forms/project_setup_form/column_test.rb:31                                       

No tests found on line 31. Valid tests to run:

test_: ProjectSetupFormColumn should set type to "String" when strings and numbers are present in a column. : m test/forms/project_setup_form/column_test.rb:399
test_: ProjectSetupFormColumn should set type to "String" when column is nil. : m test/forms/project_setup_form/column_test.rb:399
```

In the above example, no tests are found on the supplied line and are all of the tests are thought by `m` to be on line 399. 

@qrush opened #4 for this in late 2011 (!!) but closed it ~6 months later after no patches were submitted. Is this something you're still interested in patches for? If so, any recommendations on which classes one might want to start with to get the parser to correctly identify `should` as a test method?

**Comment by zamith** [comment]
I don't really use shoulda, and the project is either dead or feature complete, because it hasn't seen any new release in almost 3 years. So I'm not sure this is something worth adding support for at this time.

If there is a lot of people interested we can think about it more, but for now maybe not.

**Comment by zamith** [comment]
@davidcpell I'm closing this for now. If more people com along asking for this we can give it another look.

Thanks.
