### ISSUE TITLE
`Unresolved specs... rake >= 0.9.2.2` warning

### ISSUE THREAD

**Issue by bradmarxmoosepi** [qrush/m#59]
I keep getting the following warning:

```
$ m test/path/to/my/test_suite.rb
    > WARN: Unresolved specs during Gem::Specification.reset:
    >      rake (>= 0.9.2.2)
    > WARN: Clearing out unresolved specs.
```
My setup:

```
$ rbenv -v
    > rbenv 0.4.0-255-g29b4da7

$ ruby -v
    > ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-linux]

$ rails -v
    > Rails 4.2.0

$ gem list | grep '^m \|rake'
    > m (1.5.0)
    > rake (11.1.2, 10.5.0, 10.4.2, 0.9.2.2)
```

**Comment by zamith** [comment]
That warning results on `m` not knowing which version of rake to use, I believe, but this check does not happen on `m`, I think it happens on rubygems.

That being said, you should be able to get rid of the warning by:

1. Removing all the versions of `rake` you're not using
2. Adding `m` as a development dependency on your `Gemfile` and running the command with `bundle exec`

But regardless of the warning, does test get run?

**Comment by bradmarxmoosepi** [comment]
@zamith thanks for the reply - uninstalling unused versions of rake did not resolve the warning, but running with `bundle exec m ...` did.

The tests were being run, and it was just a warning that I wanted to address.
