### ISSUE TITLE
Multiple command line args

### ISSUE THREAD

**Issue by triplepointfive** [qrush/m#60]
Called this way

`m test/models/user_test.rb test/models/post_test.rb`

m runs tests only for the first file, would be nice if it could run tests in both files.

m version 1.5.0

**Comment by zamith** [comment]
That is something `m` does not support right now. Have you tried `rake test test/models/user_test.rb test/models/post_test.rb`? Does that work for you?

**Comment by triplepointfive** [comment]
Oh, `rake test` does the trick, thanks for advice

**Comment by zamith** [comment]
Great. That's something I might think of adding to `m`, so that you don't have to switch between one and the other, but for now I'll close the issue.

Thanks.
