### ISSUE TITLE
Question: Is it possible to mimick `fail-fast` behaviour?

### ISSUE THREAD

**Issue by jesperronn** [qrush/m#68]
For TDD I'd like the possibility to point m at a single unit-test file like so:

```
m test/models/user_test.rb
```

but I'd like to fail fast, while I implement. Is there an M equivalent to this, like for instance

```
m --fail-fast test/models/user_test.rb
```

**Comment by jesperronn** [comment]
This could be equivalent to the [Rspec `--fail-fast` option](https://relishapp.com/rspec/rspec-core/docs/command-line/fail-fast-option)

**Comment by zamith** [comment]
That would have to be a feature supported by the underlying gems. M parsers your tests to know which ones to run and then let's the various testing libraries we support know about it, it's not actually aware of what's happening.

So basically, we treat these libraries as black boxes and this feature seems like it needs to be able to hook into internals. What you can do is as for this in whatever library you use, and then M can piggyback on that to support the feature.
