### ISSUE TITLE
Running multiple files is not supported

### ISSUE THREAD

**Issue by paneq** [qrush/m#71]
The documentation says that many files can be provided.

```
m --help
Usage: m [OPTIONS] [FILES]
```

But when I go with

```
m test/unit/one_test.rb test/unit/two_test.rb
```

only the tests from the 1st file are executed.

**Comment by zamith** [comment]
At this point we do not support multiple files, so yes the help is a bit misleading.

We support running different lines in the same file or running all the tests in a directory.

**Comment by paneq** [comment]
@zamith Thanks for the clarification. Have a lovely day!
