### ISSUE TITLE
VSCode extension

### ISSUE THREAD

**Issue by faqndo97** [qrush/m#74]
I guys, How are you?

First thing, this **isn't a issue**.

I'm a Rails developer currently and in this company we use your gem to work. I'm love the utility of this gem and I use it a lot. I'm working with VSCode currently. Working all days with your gem I think that you should have an extension on VSCode environment for run tests easily.

This is the [extension](https://marketplace.visualstudio.com/items?itemName=faqndo97.m-vscode-runner) if you want use (If you use VSCode)

Maybe if you want, you can share it on the readme of the project.

What do you think?

**Comment by zamith** [comment]
Hi. Thanks a lot for the kind words. Please open a PR adding a section to the README for community extensions/integrations and I'd be happy to approve it.

**Comment by zamith** [comment]
In the meantime, I'm closing this issue. Thanks.
