### ISSUE TITLE
Passing seed to test command

### ISSUE THREAD

**Issue by mcnelson** [qrush/m#75]
Is there a way to pass `--seed` to `m`? Didn't see one in `--help` but just thought I'd ask.

**Comment by zamith** [comment]
No currently `m` does not support any flags to be passed down to the runners. This could be a interesting feature however, to allow any flags that `m` does not understand to pass-through to the underlying runner. With the understanding that some runners will not support certain flags of course.

It does have the drawback that you might share a command to run with `m` that might work in your code base and not in others, but I think it's a good trade off.

**Comment by zamith** [comment]
@mcnelson Can you give #77 a try, see if it works for your use case.

**Comment by mlt** [comment]
I'm so confused. Readme paragraph just before *Support* implies it should work, but seed is ignored. If it is not there yet, what is up with readme?

**Comment by zamith** [comment]
Currently, if the only thing being passed are extra arguments, they will be passed down to `rake test`. So, the example in the README is correct, but it won't work for all scenarios (for example it won't allow you to pass the seed and specify a test file to be run).

I get that it's probably confusing. The ideal behavior would be the one I described earlier.
