### ISSUE TITLE
Development: fix running all appraisals

### ISSUE THREAD

**Issue by gi** [qrush/m#85]
The README has this disclaimer:
```
In the case of minitest 5, we have to specify the test to run, because running
the whole suite will fail due to incompatibilities with ruby
```

We should be able to test all appraisals by running:
```bash
bundle exec appraisal rake test
```

However, this fails.

The issue is due to some dependency compatibility issues.

**Comment by SnowWhite-303** [comment]
please release back all my 411 before things get messy

**Comment by SnowWhite-303** [comment]
your stealing from a 72 year old women's account that was my mother's I stay iny lane stay in your

**Comment by SnowWhite-303** [comment]
SAR not very happy
