### ISSUE TITLE
Not work with minitest 5.16.X

### ISSUE THREAD

**Issue by zw963** [qrush/m#93]
```
/home/common/.rvm/gems/ruby-3.1.2@pryx/gems/minitest-5.16.0/lib/minitest/test.rb:70:in `srand': no implicit conversion of nil into Integer (TypeError)
        from /home/common/.rvm/gems/ruby-3.1.2@pryx/gems/minitest-5.16.0/lib/minitest/test.rb:70:in `runnable_methods'
        from /home/common/.rvm/gems/ruby-3.1.2@pryx/gems/m-1.6.0/lib/m/runners/minitest_5.rb:15:in `test_methods'
        from /home/common/.rvm/gems/ruby-3.1.2@pryx/gems/m-1.6.0/lib/m/executor.rb:90:in `block in suites'
        from /home/common/.rvm/gems/ruby-3.1.2@pryx/gems/m-1.6.0/lib/m/executor.rb:88:in `each'
        from /home/common/.rvm/gems/ruby-3.1.2@pryx/gems/m-1.6.0/lib/m/executor.rb:88:in `each_with_object'
        from /home/common/.rvm/gems/ruby-3.1.2@pryx/gems/m-1.6.0/lib/m/executor.rb:88:in `suites'
        from /home/common/.rvm/gems/ruby-3.1.2@pryx/gems/m-1.6.0/lib/m/executor.rb:61:in `tests'
        from /home/common/.rvm/gems/ruby-3.1.2@pryx/gems/m-1.6.0/lib/m/executor.rb:15:in `execute'
        from /home/common/.rvm/gems/ruby-3.1.2@pryx/gems/m-1.6.0/lib/m/runner.rb:17:in `run'
        from /home/common/.rvm/gems/ruby-3.1.2@pryx/gems/m-1.6.0/lib/m.rb:13:in `run'
        from /home/common/.rvm/gems/ruby-3.1.2@pryx/gems/m-1.6.0/bin/m:4:in `<top (required)>'
        from /home/zw963/.rvm/gems/ruby-3.1.2@pryx/bin/m:25:in `load'
        from /home/zw963/.rvm/gems/ruby-3.1.2@pryx/bin/m:25:in `<main>'
        from /home/zw963/.rvm/rubies/ruby-3.1.2/bin/ruby_executable_hooks:22:in `eval'
        from /home/zw963/.rvm/rubies/ruby-3.1.2/bin/ruby_executable_hooks:22:in `<main>'
rake aborted!
Command failed with status (1): [m test/pryx/pryx_test.rb...]
/home/common/Project/pryx/Rakefile:4:in `block in <top (required)>'
Tasks: TOP => default
(See full trace by running task with --trace)
```

The last support version is 5.15.0

**Comment by felixonmars** [comment]
Fixed by #92

**Comment by zw963** [comment]
@qrush , can we release a new version?

**Comment by zw963** [comment]
> Fixed by #92

谢谢，肥猫，最近在看 Ruby 吗？不如连 Crystal 一起看看吧。

**Comment by qrush** [comment]
@gi any chance you're up for pushing a new version here? 😅 🙏🏼

**Comment by zedtux** [comment]
Yes, please, release a new version :pray:

**Comment by searls** [comment]
@qrush / @gi -- if you're open to it, I'm willing to help maintain m and to get releases like this out the door. I had been incorrectly assuming `m` was unmaintained and thinking of building something inspired by it but it seems like it's still working (except I'm blocked by this issue)

**Comment by qrush** [comment]
@searls just invited you. :shipit:

**Comment by searls** [comment]
@qrush thanks! I can't get the tests to pass without updating bundler (which means I should commit back to the repo). Could I have commit bit too?

**Comment by searls** [comment]
Landed the change in 1.6.1. CI is not happy about it, but all tests passed locally at least.

More broadly, @qrush, if you'd like to talk about ongoing maintenance and feature development for the gem, I've got some ideas about contributing!

**Comment by qrush** [comment]
I haven’t used this gem in years. Please go ahead!

**Comment by jrochkind** [comment]
Just found this ticket after having this problem -- would love to see a release. Any chance?

**Comment by searls** [comment]
@jrochkind yes this was released in m@1.6.1

**Comment by jrochkind** [comment]
Oh, thanks! And thanks for quick response!

What had I done? Ah, I was just trying minitest in a new project today, and copy-pasted from the README  `gem 'm', '~> 1.5.0'`, so that kept me from using the up-to-date 1.6.1, oops! Thanks!

You may want to replace README copy-paste line with `gem 'm', '~> 1.6'`?  Not only updating to latest minor version, but if it gets out of date again like that, with only two version components, if someone copies-pastes it will still allow 1.7, 1.8, 1.10, etc. Whereas `~> 1.5.0` only allows 1.5.x.

**Comment by searls** [comment]
Thanks for catching this. I just removed the version pins from the README
